export const STORES = [
  // Ovenfresh
  { id:"OF001", name:"Commissary", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-63039", status: "offline" },
  { id:"OF002", name:"Keelkattalai", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-55601", status: "offline" },
  { id:"OF003", name:"Madipakkam", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-55602", status: "offline" },
  { id:"OF004", name:"Mudichur", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-55603", status: "offline" },
  { id:"OF005", name:"Mugalivakkam", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-55604", status: "offline" },
  { id:"OF006", name:"Nanganallur", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-55605", status: "offline" },
  { id:"OF007", name:"Pammal", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-55606", status: "offline" },
  { id:"OF008", name:"Perumbakkam", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-55607", status: "offline" },
  { id:"OF009", name:"Rajakilpakkam", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-55608", status: "offline" },
  { id:"OF010", name:"Ramapuram", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-55609", status: "offline" },
  { id:"OF011", name:"Test Location", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-55611", status: "offline" },
  { id:"OF012", name:"Velachery", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-60010", status: "offline" },
  { id:"OF013", name:"Nelson Manickam Rd", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-98158", status: "offline" },
  { id:"OF014", name:"Perambur", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-148164", status: "offline" },
  { id:"OF015", name:"Shriram Gateway", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-103513", status: "offline" },
  { id:"OF016", name:"Mogappair", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-162749", status: "offline" },
  { id:"OF017", name:"OMR Thoraipakkam", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-139088", status: "offline" },
  { id:"OF018", name:"T Nagar", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-162750", status: "offline" },
  { id:"OF019", name:"Amazon - Global Info City", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-63367", status: "offline" },
  { id:"OF020", name:"Commissary (POS)", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-60000", status: "offline" },
  { id:"OF021", name:"ETL Phase2", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-62570", status: "offline" },
  { id:"OF022", name:"Keelakattalai (POS)", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-60001", status: "offline" },
  { id:"OF023", name:"Madipakkam (POS)", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-60002", status: "offline" },
  { id:"OF024", name:"Mudichur (POS)", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-60003", status: "offline" },
  { id:"OF025", name:"Mugalivakkam (POS)", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-60004", status: "offline" },
  { id:"OF026", name:"Nanganallur (POS)", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-60005", status: "offline" },
  { id:"OF027", name:"Pammal (POS)", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-60006", status: "offline" },
  { id:"OF028", name:"Perumbakkam (POS)", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-60007", status: "offline" },
  { id:"OF029", name:"Rajakilpakkam (POS)", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-60008", status: "offline" },
  { id:"OF030", name:"Ramapuram (POS)", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-60009", status: "offline" },
  { id:"OF031", name:"Test Location (POS)", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-55503", status: "offline" },
  { id:"OF032", name:"Velachery (POS)", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-55612", status: "offline" },
  { id:"OF033", name:"Gateway", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-98159", status: "offline" },
  { id:"OF034", name:"Amazon - Trill", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-64588", status: "offline" },
  { id:"OF035", name:"Amazon - WTC", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-66840", status: "offline" },
  { id:"OF036", name:"Ascendas", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-99796", status: "offline" },
  { id:"OF037", name:"Marina Mall", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-171277", status: "offline" },
  { id:"OF038", name:"Nelson Manickam Road", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-99167", status: "offline" },
  { id:"OF039", name:"ODC-1", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-162650", status: "offline" },
  { id:"OF040", name:"OMR Thoraipakkam (POS)", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-139085", status: "offline" },
  { id:"OF041", name:"Perambur (POS)", brand: "Ovenfresh", city: "Chennai", location_id:"STP-L-147535", status: "offline" },

  // Paris Cakes & Desserts
  { id:"PC001", name:"Gateway", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"STP-L-150251", status: "offline" },
  { id:"PC002", name:"Madipakkam", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"STP-L-83268", status: "offline" },
  { id:"PC003", name:"Nelson Manickam Rd", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"STP-L-98160", status: "offline" },
  { id:"PC004", name:"Pammal", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"STP-L-83274", status: "offline" },
  { id:"PC005", name:"Keelkattalai", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"STP-L-83269", status: "offline" },
  { id:"PC006", name:"Mogappair", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"STP-L-166639", status: "offline" },
  { id:"PC007", name:"Mudichur", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"STP-L-83273", status: "offline" },
  { id:"PC008", name:"Mugalivakkam", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"STP-L-83275", status: "offline" },
  { id:"PC009", name:"OMR Thoraipakkam", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"STP-L-150253", status: "offline" },
  { id:"PC010", name:"Perambur", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"STP-L-150252", status: "offline" },
  { id:"PC011", name:"Perumbakkam", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"STP-L-83271", status: "offline" },
  { id:"PC012", name:"Rajakilpakkam", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"STP-L-83272", status: "offline" },
  { id:"PC013", name:"Ramapuram", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"STP-L-83276", status: "offline" },
  { id:"PC014", name:"T Nagar", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"STP-L-166640", status: "offline" },
  { id:"PC015", name:"Velachery", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"STP-L-83267", status: "offline" },
  { id:"PC016", name:"Commissary", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"STP-L-84758", status: "offline" },
  { id:"PC017", name:"Nanganallur", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"STP-L-83270", status: "offline" },
];