export const STORES = [
  // Ovenfresh
  { id:"OF001", name:"Commissary", brand: "Ovenfresh", city: "Chennai", location_id:"65749", status: "offline" },
  { id:"OF002", name:"Keelkattalai", brand: "Ovenfresh", city: "Chennai", location_id:"65740", status: "offline" },
  { id:"OF003", name:"Madipakkam", brand: "Ovenfresh", city: "Chennai", location_id:"65741", status: "offline" },
  { id:"OF004", name:"Mudichur", brand: "Ovenfresh", city: "Chennai", location_id:"65742", status: "offline" },
  { id:"OF005", name:"Mugalivakkam", brand: "Ovenfresh", city: "Chennai", location_id:"65743", status: "offline" },
  { id:"OF006", name:"Nanganallur", brand: "Ovenfresh", city: "Chennai", location_id:"65744", status: "offline" },
  { id:"OF007", name:"Pammal", brand: "Ovenfresh", city: "Chennai", location_id:"65745", status: "offline" },
  { id:"OF008", name:"Perumbakkam", brand: "Ovenfresh", city: "Chennai", location_id:"65746", status: "offline" },
  { id:"OF009", name:"Rajakilpakkam", brand: "Ovenfresh", city: "Chennai", location_id:"65747", status: "offline" },
  { id:"OF010", name:"Ramapuram", brand: "Ovenfresh", city: "Chennai", location_id:"65748", status: "offline" },
  { id:"OF011", name:"Velachery", brand: "Ovenfresh", city: "Chennai", location_id:"65752", status: "offline" },
  { id:"OF012", name:"Nelson Manickam Rd", brand: "Ovenfresh", city: "Chennai", location_id:"85915", status: "offline" },
  { id:"OF013", name:"Perambur", brand: "Ovenfresh", city: "Chennai", location_id:"119785", status: "offline" },
  { id:"OF014", name:"Shriram Gateway", brand: "Ovenfresh", city: "Chennai", location_id:"89424", status: "offline" },
  { id:"OF015", name:"Mogappair", brand: "Ovenfresh", city: "Chennai", location_id:"127158", status: "offline" },
  { id:"OF016", name:"OMR Thoraipakkam", brand: "Ovenfresh", city: "Chennai", location_id:"111411", status: "offline" },
  { id:"OF017", name:"T Nagar", brand: "Ovenfresh", city: "Chennai", location_id:"127159", status: "offline" },

  // Paris Cakes & Desserts
  { id:"PC001", name:"Gateway", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"121225", status: "offline" },
  { id:"PC002", name:"Madipakkam", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"78648", status: "offline" },
  { id:"PC003", name:"Nelson Manickam Rd", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"85916", status: "offline" },
  { id:"PC004", name:"Pammal", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"78654", status: "offline" },
  { id:"PC005", name:"Keelkattalai", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"78649", status: "offline" },
  { id:"PC006", name:"Mogappair", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"129457", status: "offline" },
  { id:"PC007", name:"Mudichur", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"78653", status: "offline" },
  { id:"PC008", name:"Mugalivakkam", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"78655", status: "offline" },
  { id:"PC009", name:"OMR Thoraipakkam", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"121227", status: "offline" },
  { id:"PC010", name:"Perambur", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"121226", status: "offline" },
  { id:"PC011", name:"Perumbakkam", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"78651", status: "offline" },
  { id:"PC012", name:"Rajakilpakkam", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"78652", status: "offline" },
  { id:"PC013", name:"Ramapuram", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"78656", status: "offline" },
  { id:"PC014", name:"T Nagar", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"129458", status: "offline" },
  { id:"PC015", name:"Velachery", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"78647", status: "offline" },
  { id:"PC016", name:"Commissary", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"79467", status: "offline" },
  { id:"PC017", name:"Nanganallur", brand: "Paris Cakes & Desserts", city: "Chennai", location_id:"78650", status: "offline" },
];